{
 "title": "Spacewalk Summary",
 "description": "Spacewalk Summary Screen",
 "tags": [
  "linux",
  "spacewalk"
 ],
 "time": { "from": "now-6h", "to": "now-30s" },
 "refresh": "1m",
 "panels": [
  { "title": "Spacewalk Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Registered Servers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT (*)\nFROM public.rhnserver"
    }
   ]
  },
  {
   "title": "Total Distinct Outstanding Errata",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select count(distinct(errata_id)) from rhnserverneededcache;  "
    }
   ]
  },
  {
   "title": "Servers Requiring Updates",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "        select count (distinct system_id) from (\n  select S.id as system_id,\n    S.org_id as org_id,\n    PN.name as package_name,\n    OPE.epoch as package_epoch,\n    OPE.version as package_version,\n    OPE.release as package_release,\n    PA.label as package_arch,\n    NPE.epoch as newer_epoch,\n    NPE.version as newer_version,\n    NPE.release as newer_release\n  from rhnServer S\n    join rhnServerNeededCache SPC on S.id=SPC.server_id\n    join rhnPackage P on SPC.package_id=P.id\n    join rhnPackageName PN on P.name_id=PN.id\n    join rhnServerPackage SP on SP.server_id=S.id and SP.name_id=P.name_id\n    join rhnPackageArch PA on SP.package_arch_id=PA.id\n    join rhnPackageEvr OPE on OPE.id=SP.evr_id\n    join rhnPackageEvr NPE on NPE.id=P.evr_id\n        ) X\n"
    }
   ]
  },
  {
   "title": "Packages Applied < 30 days",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT COUNT(id) from rhnUserActionOverview WHERE rhnUserActionOverview.action_status = 'Completed' AND earliest_action < NOW() - INTERVAL '30 days'; "
    }
   ]
  },
  {
   "title": "Outstanding Advisories",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select * from (\n                select rhnErrata.advisory_name as advisory,\n                        rhnErrata.advisory_type as type,\n                        rhnCVE.name as cve,\n                        rhnErrata.synopsis,\n                        count(*) as systems_affected\n                from rhnErrata left outer join rhnErrataCVE\n                        on rhnErrata.id = rhnErrataCVE.errata_id\n                        left outer join rhnCVE\n                        on rhnErrataCVE.cve_id = rhnCVE.id\n                        , rhnServerNeededErrataCache\n                where rhnErrata.id = rhnServerNeededErrataCache.errata_id\n                group by rhnErrata.id,\n                        rhnErrata.advisory_name,\n                        rhnErrata.advisory_type,\n                        rhnCVE.name,\n                        rhnErrata.synopsis\n                ) X\n                -- where placeholder\n                order by advisory, cve;\n"
    }
   ]
  },
  {
   "title": "Advisory List",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select * from (\n                select rhnErrata.advisory_name as advisory,\n                        rhnServerNeededErrataCache.server_id,\n                        rhnServer.name as profile_name,\n                        rhnservernetwork.hostname, trim(rhnservernetwork.ipaddr) as ip_address,\n                        trim(rhnservernetwork.ip6addr) as ipv6_address\n                from rhnErrata, rhnServer,\n                        rhnServerNeededErrataCache left outer join\n                        (\n                        select server_id, hostname, ipaddr, ip6addr\n                        from rhnservernetwork\n                        where id in (\n                                select min(id)\n                                from rhnservernetwork\n                                group by server_id\n                                )\n                        ) rhnservernetwork\n                        on rhnServerNeededErrataCache.server_id = rhnservernetwork.server_id\n                where rhnErrata.id = rhnServerNeededErrataCache.errata_id\n                        and rhnServerNeededErrataCache.server_id = rhnServer.id\n                ) X\n                -- where placeholder\n                order by advisory, server_id\n"
    }
   ]
  }
 ]
}